export const TODO_ADD = 'TODO_ADD'
export const TODO_TOGGLE = 'TODO_TOGGLE'

export const TODO_FILTER = 'TODO_FILTER'
export const VISIBILITY_SHOW_ALL = 'VISIBILITY_SHOW_ALL'
export const VISIBILITY_SHOW_ACTIVE= 'VISIBILITY_SHOW_ACTIVE'
export const VISIBILITY_SHOW_COMPLETED = 'VISIBILITY_SHOW_COMPLETED'
